/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("com.github.johnrengelman.shadow") version "6.1.0"
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.mrivanplays.com/repository/ivan/")
    }

    maven {
        url = uri("https://jcenter.bintray.com/")
    }

    maven {
      url = uri("https://m2.dv8tion.net/releases")
    }

    mavenCentral()
}

dependencies {
    implementation("net.dv8tion:JDA:4.2.1_260")
    implementation("com.mrivanplays:JDCF:1.0.6-SNAPSHOT")
    implementation("com.github.ben-manes.caffeine:caffeine:3.0.1")
    implementation("org.apache.commons:commons-text:1.9")
    implementation("org.slf4j:slf4j-simple:1.7.25")
    implementation("org.apache.httpcomponents.client5:httpclient5:5.1-beta1")
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("com.google.guava:guava:30.1.1-jre")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.0-M1")
    testImplementation("org.junit.platform:junit-platform-runner:1.8.0-M1")
    implementation("com.mrivanplays:BinClient:1.0.1-SNAPSHOT")
}

group = "org.yatopiamc"
version = "1.0-SNAPSHOT"
description = "Yatopia-Bot"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>() {
    manifest {
        attributes("Main-Class" to "org.yatopiamc.bot.YatopiaBot")
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    test {
        useJUnitPlatform()
    }
}
