/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("com.github.johnrengelman.shadow") version "6.1.0"
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.mrivanplays.com/repository/ivan/")
    }

    maven {
        url = uri("https://jcenter.bintray.com/")
    }

    mavenCentral()
}

dependencies {
    implementation("net.dv8tion:JDA:4.2.0_227")
    implementation("com.mrivanplays:JDCF:1.0.6-SNAPSHOT")
    implementation("com.github.ben-manes.caffeine:caffeine:2.8.5")
    implementation("org.apache.commons:commons-text:1.9")
    implementation("org.slf4j:slf4j-simple:1.7.25")
    implementation("org.apache.httpcomponents.client5:httpclient5:5.0.3")
    implementation("com.google.code.gson:gson:2.8.6")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.5.2")
    testImplementation("org.junit.platform:junit-platform-runner:1.5.2")
}

group = "org.yatopiamc"
version = "1.0-SNAPSHOT"
description = "Yatopia-Bot"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

application {
    mainClassName = "org.yatopiamc.bot.YatopiaBot"
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    test {
        useJUnitPlatform()
    }
}
